### ISSUE TITLE
Compatibility with DelaunayTriangulation.jl v1.0

### ISSUE THREAD

**Issue by asinghvi17** [DanielVandH/NaturalNeighbours.jl#28]
It seems like NaturalNeighbours is not currently compatible with DelaunayTriangulation v1.  Is this a sufficiently easy refactor that I could try to do it?

**Comment by DanielVandH** [comment]
Oh, I somehow completely forgot to come back to this. I believe it should be pretty easy if you want to give it a go - this package did depend on some internals of DelaunayTriangulation.jl but hopefully they are still around. If it ends up being a bit of a problem though let me know and I'll try and do it when I have some time (or just ask me if you need assistance).

**Comment by DanielVandH** [comment]
@asinghvi17 Were you able to go through with this? I will do it now otherwise.

**Comment by DanielVandH** [comment]
Not a problem. I will work on this today. Do you want me to ping you once I've done it incase you're waiting on it?

**Comment by asinghvi17** [comment]
That would be great, thanks!  I CC'ed you on the TopoPlots PR that this would probably depend on (at least for Makie v0.20.10 compat) as well.
